require Pod::Executable.execute_command('node', ['-p',
  'require.resolve(
    "react-native/scripts/react_native_pods.rb",
    {paths: [process.argv[1]]},
  )', __dir__]).strip
require_relative '../node_modules/react-native-permissions/scripts/setup.rb'
platform :ios, min_ios_version_supported
prepare_react_native_project!

linkage = ENV['USE_FRAMEWORKS']
if linkage != nil
  Pod::UI.puts "Configuring Pod with #{linkage}ally linked Frameworks".green
  use_frameworks! :linkage => linkage.to_sym
end

target 'Yogiverse' do
  config = use_native_modules!
  
  # Firebase Core
  pod 'Firebase', :modular_headers => true
  pod 'FirebaseCore', :modular_headers => true
  pod 'FirebaseCoreInternal', :modular_headers => true
  pod 'GoogleUtilities', :modular_headers => true
  
  # Firebase Messaging for Push Notifications
  pod 'FirebaseMessaging', :modular_headers => true
  pod 'FirebaseInstallations', :modular_headers => true
  
  # Firebase Analytics (optional but recommended)
  pod 'FirebaseAnalytics', :modular_headers => true
  pod 'GoogleAppMeasurement', :modular_headers => true
  
  use_react_native!(
    :path => config[:reactNativePath],
    # An absolute path to your application root.
    :app_path => "#{Pod::Config.instance.installation_root}/.."
  )

  # Setup permissions
  setup_permissions([
    'AppTrackingTransparency',
    # 'Bluetooth',
    # 'Calendars',
    # 'CalendarsWriteOnly',
    'Camera',
    'Contacts',
    # 'FaceID',
    'LocationAccuracy',
    'LocationAlways',
    'LocationWhenInUse',
    'MediaLibrary',
    # 'Microphone',
    # 'Motion',
    'Notifications',
    'PhotoLibrary',
    'PhotoLibraryAddOnly',
    # 'Reminders',
    # 'Siri',
    # 'SpeechRecognition',
    # 'StoreKit',
  ])

  post_install do |installer|    
    # https://github.com/facebook/react-native/blob/main/packages/react-native/scripts/react_native_pods.rb#L197-L202
    react_native_post_install(
      installer,
      config[:reactNativePath],
      :mac_catalyst_enabled => false,
      # :ccache_enabled => true
    )
    
    # Fix for NVM Node.js path issue with Hermes
    installer.pods_project.targets.each do |target|
      target.build_configurations.each do |config|
        # Set the correct Node.js path for Hermes
        if target.name == 'hermes-engine'
          # Try multiple Node.js paths
          node_paths = [
            '/Users/gopeshsutariya/.nvm/versions/node/v20.19.4/bin/node',
            '/opt/homebrew/bin/node',
            '/usr/local/bin/node',
            `which node`.strip
          ].select { |path| File.exist?(path) }
          
          if node_paths.any?
            config.build_settings['NODE_BINARY'] = node_paths.first
            puts "Setting NODE_BINARY to: #{node_paths.first}"
          end
        end
      end
    end
  end
end